### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by lwlondot** [mit-racecar/install_tools#4]
Trying to get the car's image using the provided script, but it says that it not there.

**Comment by Winter-Guerra** [comment]
Hi there, sorry for the wait. If I recall correctly, the online documentation refers to [this image](https://www.dropbox.com/s/d1s02mbpmhtdpry/car_22_backup.img.tar.gz?dl=1). Dropbox recently changed their URL structure and broke the link.

Best,
-Winter
