### ISSUE TITLE
Backup Image

### ISSUE THREAD

**Issue by lwlondot** [mit-racecar/install_tools#5]
I asked back in November.  The dropbox link is not active.  Looking to upload to some cars my school is working on.

**Comment by Winter-Guerra** [comment]
Hi there, sorry for the wait. If I recall correctly, the online documentation refers to [this image](https://www.dropbox.com/s/d1s02mbpmhtdpry/car_22_backup.img.tar.gz?dl=1). 

Best,
-Winter

**Comment by lwlondot** [comment]
Winter,


 Thank you for the link.  I will try tomorrow at school.  I just follow the same wget procedure but with the new  link?


Lars



-----Original Message-----

**Comment by Winter-Guerra** [comment]
The link I sent you might not work with wget. Dropbox links tend to have
browser-based redirects that mess up wget. You may have to download it
using a web browser.

Best,
-Winter

**Comment by alxtee** [comment]
Hello, Is there an updated image or install script for the Jetson TX2?
